### ISSUE TITLE
Missing _dlopen() required by darkcoin 

### ISSUE THREAD

**Issue by boblq** [barnumbirr/darkcoin-api#2]
import darkcoin 

immediately leads to 

```
Traceback (most recent call last):
  File "C:/Python27/Scripts/test.py", line 1, in <module>
    import darkcoin
  File "C:\Python27\lib\site-packages\darkcoin\__init__.py", line 17, in <module>
    import darkcoin_utils
  File "C:\Python27\lib\site-packages\darkcoin\darkcoin_utils.py", line 21, in <module>
    ssl = ctypes.cdll.LoadLibrary (ctypes.util.find_library ('ssl') or 'libeay32')
  File "C:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
```

I note that the _dlopen appears to be in the source file C:\Python27\Lib\ctypes__init__ which apparently is not compiled into the binary by default into the binary that I dl. So do I have to build from source in order to get this ... or is their some other readily available mechanism?

**Comment by c0ding** [comment]
Hi there,

from what I understand in this stacktrace the issue seems to be with ctypes, not with _dlopen. 
This throws an error:
```
ssl = ctypes.cdll.LoadLibrary (ctypes.util.find_library ('ssl') or 'libeay32')
```
Probably a missing DLL. I'll have to research this when I get home from work tonight but I don't have a Windows computer to test the code on.

Cheers.

**Comment by boblq** [comment]
Thanks.

Lucky man, no Windows computer.

**Comment by c0ding** [comment]
You can find  the missing DLL (libeay32.dll) as part of the Windows version of [OpenSSL for Windows]. (http://slproweb.com/products/Win32OpenSSL.html).
Could you try loading it with something like:
```
ctypes.windll.LoadLibrary("C:\\path\\to\\DLL.dll")
```
or
```
ctypes.windll.LoadLibrary("C:/path/to/DLL.dll")
```
Hope this works.

**Comment by boblq** [comment]
search on my box yields no hits for either ssl or libeay32
I have located and dl the libeay32.
Now I need to figure out where to put it.
Ok. I tried C;\Windows\System32
But no joy :(

Maybe some registry thing ...

Now I find libeay32.dll is installed in some games off on the G: disk
and here
C:\Program Files\AVAST Software\Avast

But still no joy ... maybe there is a problem in ctypes as you have
suggested.

HTH,

BobLQ

**Comment by c0ding** [comment]
Have you tried installing the whole OpenSSL package?
The path to the DLL should be an absolute path, like this:
```
C:\Windows\System32\something\another_something\libeay32.dll
```
You may have to escape the backslashes.

**Comment by boblq** [comment]
Hmm this is useful
http://lifehacker.com/269063/install-a-dll-file-in-windows

So I get a command widow and run
regsvr32 libeay32.dll

And it says may not be compatible 32 vs 64 bit

I look and damn! This machine has a 64 bit OS.

Hm ... ctypes is looking for 'ssl' or 'libeay32' I guess I need to get back
and look for the 64 bit version ...

**Comment by boblq** [comment]
Now https://www.openssl.org/ fails to open DNS servers here clog up around
5:00 PM. I will quit for a while  ;(

PITA, diba?

**Comment by c0ding** [comment]
The sources for OpenSSL for Windows are [located here](http://slproweb.com/products/Win32OpenSSL.html).

**Comment by boblq** [comment]
One last take

I find
http://stackoverflow.com/questions/4897685/how-do-i-register-a-dll-file-on-windows-7-64-bit

I found this so I try moving libeay32.dll to C:\Windows\SysWOW64
then regsvr32 libeay32.dll

I get message libeay32.dll loaded but entry-point DllRegisterServer was not
found.

I need to take a break and read the top link closely when fresh. It seems
to be a typical M$ mess.

**Comment by boblq** [comment]
I will return and check out total install later as well as the path I was
going down. Thanks for the suggestions.

I think I am getting close. Hopefully at th eend we will have something
that makes life easier for those who follow us.

**Comment by c0ding** [comment]
No worries, take your time. I'll be here if you need help. :)

**Comment by barnumbirr** [comment]
@boblq Do you have a status update on this issue? Did you manage to solve the OpenSSL issue?

Cheers.

**Comment by boblq** [comment]
No. I wanted to finish it off shortly after opening the issue because I was
expecting to have no time afterward. And that is what happened. I have been
both traveling and in constant meetings since then.

I have not even found time until now to look at the issue. I am back home
now catching up on a number of projects. I will take a look later today.

Onward,

BobLQ

**Comment by barnumbirr** [comment]
No feedback in a month. Closed.
